# Generated by Django 5.1.4 on 2024-12-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_full_name_customuser_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
