# Generated by Django 5.1.4 on 2025-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Distributor', 'Distributor'), ('Fanchise', 'Franchise'), ('SalesPerson', 'Sales Person'), ('Others', 'Others')], max_length=20),
        ),
    ]
