# Generated by Django 5.1.4 on 2025-02-19 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_franchise_customuser_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.distributor'),
        ),
    ]
