# Generated by Django 5.1.4 on 2025-02-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.factory'),
        ),
    ]
