# Generated by Django 5.1.4 on 2025-03-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.factory'),
        ),
    ]
