# Generated by Django 5.1.4 on 2025-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Distributor', 'Distributor'), ('Franchise', 'Franchise'), ('SalesPerson', 'Sales Person'), ('Treatment Staff', 'Treatment Staff'), ('Logistics', 'Logistics'), ('Packaging', 'Packaging'), ('Others', 'Others')], max_length=20),
        ),
    ]
