# Generated by Django 5.1.4 on 2025-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logistics',
            name='address',
        ),
        migrations.AlterField(
            model_name='logistics',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logistics',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
