# Generated by Django 5.1.4 on 2025-08-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_customuser_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'Super Admin'), ('Distributor', 'Distributor'), ('Franchise', 'Franchise'), ('SalesPerson', 'Sales Person'), ('Treatment Staff', 'Treatment Staff'), ('YDM_Logistics', 'YDM Logistics'), ('YDM_Rider', 'YDM Rider'), ('YDM_Operator', 'YDM Operator'), ('Packaging', 'Packaging'), ('Others', 'Others')], max_length=20),
        ),
    ]
