# Generated by Django 5.1.4 on 2025-08-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_orderchangelog_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderchangelog',
            options={'ordering': ['changed_at']},
        ),
    ]
