# Generated by Django 5.1.4 on 2025-08-27 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_orderchangelog_options'),
        ('sales', '0067_alter_order_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderchangelog',
            name='logistics_o_order_i_61f388_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderchangelog',
            name='logistics_o_user_id_b87393_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderchangelog',
            name='logistics_o_new_sta_f1f856_idx',
        ),
        migrations.AddIndex(
            model_name='orderchangelog',
            index=models.Index(fields=['order', 'changed_at'], name='logistics_o_order_i_e03bec_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchangelog',
            index=models.Index(fields=['user', 'changed_at'], name='logistics_o_user_id_5b2297_idx'),
        ),
        migrations.AddIndex(
            model_name='orderchangelog',
            index=models.Index(fields=['new_status', 'changed_at'], name='logistics_o_new_sta_ae7f5f_idx'),
        ),
    ]
