# Generated by Django 5.1.4 on 2025-09-14 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('logistics', '0005_assignorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('digital_wallet', 'Digital Wallet')], default='cash', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='account.franchise')),
                ('paid_by', models.ForeignKey(limit_choices_to={'role__in': ['YDM_Logistics', 'YDM_Operator', 'SuperAdmin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['franchise', '-payment_date'], name='logistics_f_franchi_90df58_idx'), models.Index(fields=['paid_by', '-payment_date'], name='logistics_f_paid_by_653943_idx')],
            },
        ),
    ]
