# Generated by Django 5.1.4 on 2025-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_invoice_approved_by_alter_invoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FranchisePaymentLog',
        ),
    ]
