# Generated by Django 5.1.4 on 2026-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_invoice_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignorder',
            name='is_rider_verified',
            field=models.BooleanField(default=False),
        ),
    ]
