# Generated by Django 5.1.4 on 2026-06-26 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_ridercommissionrate_riderpayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ridercommissionrate',
            options={'ordering': ['order_min_amount']},
        ),
        migrations.RenameField(
            model_name='ridercommissionrate',
            old_name='max_amount',
            new_name='order_max_amount',
        ),
        migrations.RenameField(
            model_name='ridercommissionrate',
            old_name='min_amount',
            new_name='order_min_amount',
        ),
    ]
