# Generated by Django 5.1.4 on 2026-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_ridercommissionrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignorder',
            name='ydm_delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Logistics delivery charge set by the rider based on delivery address (separate from franchise delivery_charge)', max_digits=10, null=True),
        ),
    ]
