# Generated by Django 5.1.4 on 2026-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_assignorder_ydm_delivery_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='YdmLogisticsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inside_ringroad_charge', models.DecimalField(decimal_places=2, default=100.0, help_text='YDM delivery charge for inside ringroad deliveries.', max_digits=10)),
                ('outside_ringroad_charge', models.DecimalField(decimal_places=2, default=150.0, help_text='YDM delivery charge for outside ringroad deliveries.', max_digits=10)),
            ],
            options={
                'verbose_name': 'YDM Logistics Setting',
                'verbose_name_plural': 'YDM Logistics Settings',
            },
        ),
        migrations.AddField(
            model_name='assignorder',
            name='delivery_location_type',
            field=models.CharField(blank=True, choices=[('Inside Ringroad', 'Inside Ringroad'), ('Outside Ringroad', 'Outside Ringroad')], db_index=True, help_text='Delivery location type selected by the rider (Inside Ringroad or Outside Ringroad).', max_length=50, null=True),
        ),
    ]
