# Generated by Django 5.1.4 on 2026-06-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_ydmlogisticssetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignorder',
            name='ydm_cancelled_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Logistics cancelled charge set when the order is assigned or updated (separate from franchise delivery_charge)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ydmlogisticssetting',
            name='cancelled_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='YDM charge for cancelled / returned deliveries.', max_digits=10),
        ),
    ]
