# Generated by Django 5.1.7 on 2026-06-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0093_historicaldataconfig_base_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='sales_game.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='active_condition',
            field=models.ForeignKey(blank=True, help_text='The currently selected/active condition for this game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sales_game.gamecondition'),
        ),
        migrations.CreateModel(
            name='GameConditionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('product', 'Specific Product'), ('keyword', 'Keyword in Product Name')], default='product', max_length=20)),
                ('keyword', models.CharField(blank=True, help_text='Case-insensitive partial match on product name', max_length=100, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity required')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sales_game.gamecondition')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='GameWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_game.gamecondition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_game.game')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_winners', to='sales.order')),
            ],
        ),
    ]
