# Generated by Django 5.1.4 on 2026-06-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecondition',
            name='name',
        ),
    ]
