# Generated by Django 5.1.4 on 2026-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_game', '0002_remove_gamecondition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
