# Generated by Django 5.1.4 on 2026-02-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_received_fb', models.IntegerField(blank=True, null=True)),
                ('message_received_whatsapp', models.IntegerField(blank=True, null=True)),
                ('message_received_tiktok', models.IntegerField(blank=True, null=True)),
                ('call_received', models.IntegerField(blank=True, null=True)),
                ('customer_follow_up', models.IntegerField(blank=True, null=True)),
                ('new_customer', models.IntegerField(blank=True, null=True)),
                ('daily_dollar_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_to_package', models.IntegerField(blank=True, null=True)),
                ('free_treatment', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.franchise')),
            ],
        ),
    ]
