# Generated by Django 5.1.4 on 2026-02-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.franchise'),
        ),
    ]
