# Generated by Django 5.1.4 on 2026-03-18 05:52

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def populate_date_field(apps, schema_editor):
    Report = apps.get_model('statistic', 'Report')
    for report in Report.objects.all():
        if report.created_at:
            dt = report.created_at
            if timezone.is_aware(dt):
                dt = timezone.localtime(dt)
            report.date = dt.date() - timedelta(days=1)
            report.save(update_fields=['date'])

def reverse_populate_date_field(apps, schema_editor):
    Report = apps.get_model('statistic', 'Report')
    Report.objects.update(date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_report_date'),
    ]

    operations = [
        migrations.RunPython(populate_date_field, reverse_code=reverse_populate_date_field),
    ]
