# Generated by Django 5.1.4 on 2026-07-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='YDMLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('franchise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ydm_logistics', to='account.franchise')),
            ],
            options={
                'verbose_name': 'YDM Logistics',
                'verbose_name_plural': 'YDM Logistics',
            },
        ),
    ]
