# Generated by Django 5.1.4 on 2026-09-22 05:11

import core.utils.s3bucket
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], db_index=True, default='online', max_length=50)),
                ('payment_screenshot', models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='treatment/payments/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='customertreatment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['day_number', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='customertreatment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='image',
            name='status',
        ),
        migrations.AddField(
            model_name='customertreatment',
            name='package',
            field=models.CharField(blank=True, choices=[('one_month', '1 Month - Rs. 5000'), ('two_month', '2 Month - Rs. 8000'), ('three_month', '3 Month - Rs. 12000')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customertreatment',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='treatment/payments/'),
        ),
        migrations.AddField(
            model_name='customertreatment',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for providing free service', null=True),
        ),
        migrations.AddField(
            model_name='customertreatment',
            name='service_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_treatments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertreatment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total treatment fee (defaults to package price if package member)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customertreatment',
            name='treatment_type',
            field=models.CharField(choices=[('package_member', 'Package Member'), ('bottle_member', 'Bottle Member'), ('home_oil', 'Home Oil'), ('one_time_service', 'One Time Service'), ('free_service', 'Free Service')], db_index=True, default='one_time_service', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, help_text='Day number for periodic treatment tracking (e.g., Day 1, Day 4, Day 8)', null=True),
        ),
        migrations.AlterField(
            model_name='customertreatment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertreatment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='customertreatment',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='treatment/images/'),
        ),
        migrations.AddIndex(
            model_name='customertreatment',
            index=models.Index(fields=['treatment_type', 'created_at'], name='treatment_c_treatme_293f90_idx'),
        ),
        migrations.AddIndex(
            model_name='customertreatment',
            index=models.Index(fields=['service_by', 'treatment_type'], name='treatment_c_service_4744a4_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['customer_treatment', 'day_number'], name='treatment_i_custome_2c8aed_idx'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_payments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='customer_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='treatment.customertreatment'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['customer_treatment', 'payment_date'], name='treatment_p_custome_4fa190_idx'),
        ),
    ]
