# Generated by Django 5.1.4 on 2026-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_paymenthistory_alter_customertreatment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertreatment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], help_text='Payment method (Cash, Online)', max_length=50, null=True),
        ),
    ]
