# Generated by Django 5.1.4 on 2026-09-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_customertreatment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertreatment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid on customer registration', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customertreatment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total fee to be paid for the treatment', max_digits=10, null=True),
        ),
    ]
