# Generated by Django 5.1.4 on 2026-09-22 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('treatment', '0004_customertreatment_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customertreatment',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_treatments', to='account.franchise'),
        ),
        migrations.AddIndex(
            model_name='customertreatment',
            index=models.Index(fields=['franchise', 'treatment_type'], name='treatment_c_franchi_907bc3_idx'),
        ),
    ]
