# Generated by Django 5.1.4 on 2026-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darazsellerstore',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='darazsellerstore',
            name='access_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='darazsellerstore',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='darazsellerstore',
            name='refresh_token_expires_at',
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_address_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_address_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_address_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_address_type',
            field=models.CharField(default='work', max_length=50),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='origin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='shipper_external_warehouse_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='shipper_platform_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='shipper_seller_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='darazsellerstore',
            name='shipper_warehouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
