# Generated by Django 5.1.4 on 2026-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0002_remove_darazsellerstore_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarazLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('l3_id', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(db_index=True, max_length=255)),
                ('l4_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daraz Location',
                'verbose_name_plural': 'Daraz Locations',
                'ordering': ['city', 'area'],
            },
        ),
    ]
