# Generated by Django 5.1.4 on 2025-09-15 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0001_initial'),
        ('sales', '0071_alter_order_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount_of_card',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='how_know_about_campaign',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='imei',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ntc_recharge_card',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_model',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product_purchased',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='recharge_card',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sale_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sold_area',
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='sales.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
