# Generated by Django 5.1.4 on 2025-09-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0003_remove_customer_order_remove_customer_sales_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
