# Generated by Django 5.1.4 on 2025-09-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('lucky_draw', '0004_remove_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckydrawsystem',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.franchise'),
        ),
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lucky_draw.organization'),
        ),
    ]
