# Generated by Django 5.1.4 on 2025-09-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0005_luckydrawsystem_franchise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephoneoffer',
            name='valid_condition',
        ),
        migrations.RemoveField(
            model_name='mobilephoneoffer',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='mobilephoneoffer',
            name='lucky_draw_system',
        ),
        migrations.RemoveField(
            model_name='rechargecard',
            name='lucky_draw_system',
        ),
        migrations.RemoveField(
            model_name='rechargecardoffer',
            name='valid_condition',
        ),
        migrations.RemoveField(
            model_name='rechargecardoffer',
            name='lucky_draw_system',
        ),
        migrations.RemoveField(
            model_name='luckydrawsystem',
            name='how_to_participate',
        ),
        migrations.RemoveField(
            model_name='luckydrawsystem',
            name='redeem_condition',
        ),
        migrations.RemoveField(
            model_name='luckydrawsystem',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='luckydrawsystem',
            name='type',
        ),
        migrations.DeleteModel(
            name='IMEINO',
        ),
        migrations.DeleteModel(
            name='MobileOfferCondition',
        ),
        migrations.DeleteModel(
            name='MobilePhoneOffer',
        ),
        migrations.DeleteModel(
            name='RechargeCard',
        ),
        migrations.DeleteModel(
            name='RechargeCardCondition',
        ),
        migrations.DeleteModel(
            name='RechargeCardOffer',
        ),
    ]
