# Generated by Django 5.1.4 on 2025-09-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0006_remove_mobilephoneoffer_valid_condition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectronicsShopOffer',
            new_name='Offer',
        ),
        migrations.RenameModel(
            old_name='ElectronicOfferCondition',
            new_name='OfferCondition',
        ),
        migrations.RemoveField(
            model_name='fixoffer',
            name='imei_no',
        ),
    ]
