# Generated by Django 5.1.4 on 2025-09-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0007_rename_electronicsshopoffer_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='uuid_key',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
