# Generated by Django 5.1.4 on 2025-09-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0008_alter_luckydrawsystem_uuid_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='uuid_key',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
