# Generated by Django 5.1.7 on 2026-06-16 09:15

import core.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw', '0009_alter_luckydrawsystem_uuid_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftitem',
            name='image',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='gift_items/'),
        ),
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='background_image',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='lucky_draws/'),
        ),
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='hero_image',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='lucky_draws/'),
        ),
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='main_offer_stamp_image',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='lucky_draws/'),
        ),
        migrations.AlterField(
            model_name='luckydrawsystem',
            name='qr',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='lucky_draws/'),
        ),
    ]
