# Generated by Django 5.1.4 on 2025-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_dash_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dash',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
