# Generated by Django 5.1.4 on 2025-09-21 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('lucky_draw', '0004_remove_customer_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_group', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='sales_group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_lucky_draw', models.BooleanField(default=False)),
                ('has_sales_fest', models.BooleanField(default=False)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.franchise')),
                ('lucky_draw_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lucky_draw.luckydrawsystem')),
                ('sales_group', models.ManyToManyField(blank=True, null=True, to='sales_fest.salesgroup')),
            ],
        ),
    ]
