# Generated by Django 5.1.4 on 2025-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_fest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festconfig',
            name='sales_group',
            field=models.ManyToManyField(blank=True, to='sales_fest.salesgroup'),
        ),
    ]
