# Generated by Django 5.1.4 on 2025-09-21 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_fest', '0002_alter_festconfig_sales_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='sales_group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
