# Generated by Django 5.1.4 on 2025-09-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('sales_fest', '0003_alter_salesgroup_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festconfig',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.franchise'),
        ),
    ]
