# Generated by Django 5.1.4 on 2025-09-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('lucky_draw', '0004_remove_customer_phone_number'),
        ('sales_fest', '0004_alter_festconfig_franchise'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='festconfig',
            constraint=models.UniqueConstraint(fields=('franchise',), name='unique_franchise_fest_config'),
        ),
    ]
