# Generated by Django 5.1.4 on 2024-12-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_commission_amount_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='amount',
            new_name='rate',
        ),
    ]
