# Generated by Django 5.1.4 on 2025-02-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_franchise_customuser_franchise'),
        ('sales', '0008_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='account.franchise'),
        ),
    ]
