# Generated by Django 5.1.4 on 2025-02-19 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_franchise_distributor'),
        ('sales', '0009_inventory_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='account.distributor'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='account.franchise'),
        ),
    ]
