# Generated by Django 5.1.4 on 2025-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_inventory_factory_inventoryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='', max_length=255),
        ),
    ]
