# Generated by Django 5.1.4 on 2025-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_inventoryrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
