# Generated by Django 5.1.4 on 2025-02-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_inventoryrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
