# Generated by Django 5.1.4 on 2025-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_orderproduct_discount_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
