# Generated by Django 5.1.4 on 2025-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_inventoryrequest_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
