# Generated by Django 5.1.4 on 2025-02-20 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_factory'),
        ('sales', '0018_inventory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='distributor',
        ),
        migrations.AddField(
            model_name='commission',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='account.franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='franchise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.franchise'),
            preserve_default=False,
        ),
    ]
