# Generated by Django 5.1.4 on 2025-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
