# Generated by Django 5.1.4 on 2025-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('ready_to_dispatch', 'Ready to Dispatch'), ('damaged_returned', 'Damaged/Returned')], default='incoming', max_length=255, null=True),
        ),
    ]
