# Generated by Django 5.1.4 on 2025-02-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_inventorychangelog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorychangelog',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='sales.inventory'),
        ),
    ]
