# Generated by Django 5.1.4 on 2025-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_inventorychangelog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorychangelog',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('deleted', 'Deleted'), ('restore', 'Restore')], default='update', max_length=20),
        ),
    ]
