# Generated by Django 5.1.4 on 2025-03-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_factory'),
        ('sales', '0030_alter_order_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.distributor'),
        ),
        migrations.AddField(
            model_name='order',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.factory'),
        ),
    ]
