# Generated by Django 5.1.4 on 2025-03-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_alter_inventorychangelog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
