# Generated by Django 5.1.4 on 2025-03-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
    ]
