# Generated by Django 5.1.4 on 2025-03-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_factory'),
        ('sales', '0037_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.distributor'),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.factory'),
        ),
    ]
