# Generated by Django 5.1.4 on 2025-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_inventoryrequest_distributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
