# Generated by Django 5.1.4 on 2025-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_alter_order_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
