# Generated by Django 5.1.4 on 2025-03-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_promocode_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
