# Generated by Django 5.1.4 on 2025-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_alter_order_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
