# Generated by Django 5.1.4 on 2025-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_order_prepaid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Sent to Dash', 'Sent to Dash'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned By Customer', 'Returned By Customer'), ('Returned By Dash', 'Returned By Dash'), ('Return Pending', 'Return Pending')], default='Pending', max_length=255),
        ),
    ]
