# Generated by Django 5.1.4 on 2025-05-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Prepaid', 'Prepaid'), ('Office Visit', 'Office Visit')], max_length=255),
        ),
    ]
