# Generated by Django 5.1.4 on 2025-05-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
