# Generated by Django 5.1.4 on 2025-05-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_choice',
            field=models.CharField(blank=True, choices=[('Inside valley', 'Inside valley'), ('Outside valley', 'Outside valley')], max_length=255, null=True),
        ),
    ]
