# Generated by Django 5.1.4 on 2025-05-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_order_delivery_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_choice',
            new_name='delivery_type',
        ),
    ]
