# Generated by Django 5.1.4 on 2025-05-19 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_logistics'),
        ('sales', '0050_rename_delivery_choice_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.logistics'),
        ),
    ]
