# Generated by Django 5.1.4 on 2025-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_order_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Prepaid', 'Prepaid'), ('Office Visit', 'Office Visit'), ('Indrive', 'Indrive')], max_length=255),
        ),
    ]
