# Generated by Django 5.1.4 on 2025-06-06 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_alter_order_created_at_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 6, 5, 40, 36, 103370, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
