# Generated by Django 5.1.4 on 2025-06-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sales.location'),
        ),
    ]
