# Generated by Django 5.1.4 on 2025-06-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_order_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='location',
            new_name='dash_location',
        ),
    ]
