# Generated by Django 5.1.4 on 2025-06-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_rename_location_order_dash_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dash_tracking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
