# Generated by Django 5.1.4 on 2025-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_order_dash_tracking_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_data', models.BooleanField(default=False)),
            ],
        ),
    ]
