# Generated by Django 5.1.4 on 2025-08-27 06:20

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0062_databasemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, default=sales.models.generate_order_id, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('DASH', 'DASH')], default='YDM', max_length=255, null=True),
        ),
    ]
