# Generated by Django 5.1.4 on 2025-08-27 06:42

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_order_order_code_alter_order_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, default=sales.models.generate_order_id, max_length=20, null=True),
        ),
    ]
