# Generated by Django 5.1.4 on 2025-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0067_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('DASH', 'DASH'), ('Pick and Drop', 'Pick and Drop'), ('NPM', 'NPM')], default='YDM', max_length=255, null=True),
        ),
    ]
