# Generated by Django 5.1.4 on 2025-09-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0068_alter_order_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Verified', 'Verified'), ('Sent to Dash', 'Sent to Dash'), ('Sent to YDM', 'Sent to YDM'), ('Delivered', 'Delivered'), ('Indrive', 'Indrive'), ('Cancelled', 'Cancelled'), ('Returned By Customer', 'Returned By Customer'), ('Returned By Dash', 'Returned By Dash'), ('Return Pending', 'Return Pending'), ('Out For Delivery', 'Out For Delivery'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=255),
        ),
    ]
