# Generated by Django 5.1.4 on 2025-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0071_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery_free',
            field=models.BooleanField(default=False),
        ),
    ]
