# Generated by Django 5.1.4 on 2025-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0072_order_is_delivery_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('DASH', 'DASH'), ('Pick and Drop', 'Pick and Drop')], max_length=255, null=True),
        ),
    ]
