# Generated by Django 5.1.4 on 2025-11-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0073_location_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('DASH', 'DASH'), ('PicknDrop', 'Pick and Drop')], max_length=255, null=True),
        ),
    ]
