# Generated by Django 5.1.4 on 2025-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0074_alter_location_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop'), ('NCM', 'NCM')], default='YDM', max_length=255, null=True),
        ),
    ]
