# Generated by Django 5.1.4 on 2025-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0075_alter_location_logistics_alter_order_logistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dash_location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='order',
            name='pickndrop_city_area',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
