# Generated by Django 5.1.4 on 2025-11-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0076_rename_dash_location_order_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dash_tracking_code',
            new_name='tracking_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickndrop_city_area',
        ),
    ]
