# Generated by Django 5.1.4 on 2025-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0078_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Verified', 'Verified'), ('Sent to Dash', 'Sent to Dash'), ('Sent to YDM', 'Sent to YDM'), ('Sent to PicknDrop', 'Sent to PicknDrop'), ('Delivered', 'Delivered'), ('Indrive', 'Indrive'), ('Cancelled', 'Cancelled'), ('Returned By Customer', 'Returned By Customer'), ('Returned By Dash', 'Returned By Dash'), ('Returned By YDM', 'Returned By YDM'), ('Returned By PicknDrop', 'Returned By PicknDrop'), ('Return Pending', 'Return Pending'), ('Out For Delivery', 'Out For Delivery'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=255),
        ),
    ]
