# Generated by Django 5.1.4 on 2026-01-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0082_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
