# Generated by Django 5.1.4 on 2026-02-09 08:48

from django.db import migrations


def update_media_paths(apps, schema_editor):
    """
    Update all old media file paths to have the path yachuSales/
    """
    Product = apps.get_model("sales", "Product")
    Order = apps.get_model("sales", "Order")

    # Update Product images
    products_updated = 0
    for product in Product.objects.all():
        if product.image:
            old_path = str(product.image)

            # Skip if already has the correct path
            if old_path.startswith("yachuSales/"):
                continue

            # Extract just the filename from various possible old formats
            filename = old_path

            # Remove common old prefixes
            old_prefixes = [
                "public/",
                "yachuSales/",
                "products/",
                "media/",
            ]

            for prefix in old_prefixes:
                if filename.startswith(prefix):
                    filename = filename[len(prefix) :]

            # Set the new path
            new_path = f"yachuSales/{filename}"
            product.image = new_path
            product.save(update_fields=["image"])
            products_updated += 1

    # Update Order payment screenshots
    orders_updated = 0
    for order in Order.objects.all():
        if order.payment_screenshot:
            old_path = str(order.payment_screenshot)

            # Skip if already has the correct path
            if old_path.startswith("yachuSales/"):
                continue

            # Extract just the filename from various possible old formats
            filename = old_path

            # Remove common old prefixes
            old_prefixes = [
                "public/",
                "yachuSales/",
                "payment_screenshots/",
                "media/",
            ]

            for prefix in old_prefixes:
                if filename.startswith(prefix):
                    filename = filename[len(prefix) :]

            # Set the new path
            new_path = f"yachuSales/{filename}"
            order.payment_screenshot = new_path
            order.save(update_fields=["payment_screenshot"])
            orders_updated += 1

    print(
        f"Updated {products_updated} product images and {orders_updated} order payment screenshots"
    )


def reverse_migration(apps, schema_editor):
    """
    This is a data migration that cannot be easily reversed.
    You would need to manually restore the old paths if needed.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0083_order_country_code"),
    ]

    operations = [
        migrations.RunPython(update_media_paths, reverse_migration),
    ]
