# Generated by Django 5.1.4 on 2026-02-09 09:26

import core.utils.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0084_update_media_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, storage=core.utils.s3bucket.PublicMediaStorage(), upload_to='products/'),
        ),
    ]
