# Generated by Django 5.1.4 on 2026-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0086_fix_double_yachu_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_factory_ingredient',
            field=models.BooleanField(default=False),
        ),
    ]
