# Generated by Django 5.1.4 on 2026-02-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0087_product_is_factory_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('raw_material', 'Raw Material'), ('ready_to_dispatch', 'Ready to Dispatch'), ('stickers', 'Stickers'), ('bottles', 'Bottles'), ('damaged_returned', 'Damaged/Returned')], default='ready_to_dispatch', max_length=255, null=True),
        ),
    ]
