# Generated by Django 5.1.4 on 2026-02-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0088_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('sticker', 'Sticker'), ('raw_material', 'Raw Material'), ('finished_product', 'Finished Product')], default='finished_product', max_length=255),
        ),
    ]
