# Generated by Django 5.1.4 on 2026-02-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0089_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('bottles', 'Bottle'), ('stickers', 'Sticker'), ('raw_material', 'Raw Material'), ('finished_product', 'Finished Product')], default='finished_product', max_length=255),
        ),
    ]
