# Generated by Django 5.1.4 on 2026-02-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('sales', '0090_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.franchise'),
        ),
        migrations.CreateModel(
            name='InventoryRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('inventory_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='sales.inventoryrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
    ]
