# Generated by Django 5.1.4 on 2026-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0091_remove_inventoryrequest_distributor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_ago', models.PositiveIntegerField(default=6, help_text='Number of months to go back from today.')),
                ('base_week', models.PositiveIntegerField(default=1, help_text='The starting week for rotation (1st of month = base_week).')),
            ],
        ),
    ]
