# Generated by Django 5.1.4 on 2026-03-17 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0092_historicaldataconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldataconfig',
            name='base_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='The date when base_week was last set (used for daily increment).'),
        ),
    ]
