# Generated by Django 5.1.4 on 2026-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0093_historicaldataconfig_base_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('YDM_OLD', 'YDM OLD'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('YDM_OLD', 'YDM OLD'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop'), ('NCM', 'NCM')], default='YDM', max_length=255, null=True),
        ),
    ]
