# Generated by Django 5.1.4 on 2026-06-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0094_alter_location_logistics_alter_order_logistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('YDM_OLD', 'YDM OLD'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop'), ('NCM', 'NCM'), ('DARAZ', 'DARAZ')], default='YDM', max_length=255, null=True),
        ),
    ]
