# Generated by Django 5.1.4 on 2026-07-02 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0003_darazlocation'),
        ('sales', '0095_alter_order_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daraz_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daraz_orders', to='daraz.darazlocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Verified', 'Verified'), ('Sent to Dash', 'Sent to Dash'), ('Sent to YDM', 'Sent to YDM'), ('Sent to Daraz', 'Sent to Daraz'), ('Sent to PicknDrop', 'Sent to PicknDrop'), ('Delivered', 'Delivered'), ('Indrive', 'Indrive'), ('Cancelled', 'Cancelled'), ('Returned By Customer', 'Returned By Customer'), ('Returned By Dash', 'Returned By Dash'), ('Returned By YDM', 'Returned By YDM'), ('Returned By PicknDrop', 'Returned By PicknDrop'), ('Returned By Daraz', 'Returned By Daraz'), ('Return Pending', 'Return Pending'), ('Out For Delivery', 'Out For Delivery'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=255),
        ),
    ]
