# Generated by Django 5.1.4 on 2026-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0096_order_daraz_location_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('YDM_OLD', 'YDM OLD'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop'), ('NCM', 'NCM'), ('Daraz', 'Daraz')], default='YDM', max_length=255, null=True),
        ),
    ]
