# Generated by Django 5.1.4 on 2026-07-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0097_alter_order_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
