# Generated by Django 5.1.4 on 2026-10-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0098_order_package_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, choices=[('YDM', 'YDM'), ('YDM_OLD', 'YDM OLD'), ('DASH', 'DASH'), ('PicknDrop', 'PicknDrop'), ('NCM', 'NCM'), ('Daraz', 'Daraz'), ('pathao', 'pathao')], default='YDM', max_length=255, null=True),
        ),
    ]
