# Generated by Django 5.1.4 on 2025-11-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_role'),
        ('pickndrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickndrop',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.franchise'),
        ),
    ]
