# Generated by Django 5.1.4 on 2025-11-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickndrop', '0002_pickndrop_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickndrop',
            name='client_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
